n = input('Digite algo: ')
print('É do tipo {}'.format(type(n)))
print('É alfabético? {}'.format(n.isalpha()))
print('O char é ASCII? {}'.format(n.isascii()))
print('É dígito? {}'.format(n.isdigit()))
print('É decimal? {}'.format(n.isdecimal()))
print('É um identificador reservado? {}'.format(n.isidentifier()))
print('Está lowercase? {}'.format(n.islower()))
print('É numérico? {}'.format(n.isnumeric()))
print('É printável? {}'.format(n.isprintable()))
print('É título? {}'.format(n.istitle()))
print('Tem espaços? {}'.format(n.isspace()))
print('É uppercase? {}'.format(n.isupper()))
